apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nkru03ifw-python 
  janus-idp.io/tekton: nkru03ifw-python
  backstage.io/kubernetes-id: nkru03ifw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkru03ifw-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  